// <auto-generated />
using System;
using BlazorIoTBridge.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorIoTBridge.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211105022318_Info-Id-2-Key")]
    partial class InfoId2Key
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BlazorIoTBridge.Shared.Info", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DEVICE_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_COMPATIBILITY_ENDPOINT")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_COMPATIBILITY_PATH")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_CONNECTION_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_SAS_KEY")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FwdTelemetrythruBlazorSvr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HUB_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("IOTHUB_DEVICE_CONN_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("IOTHUB_HUB_CONN_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("SERVICE_CONNECTION_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("SHARED_ACCESS_KEY_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("SYMMETRIC_KEY")
                        .HasColumnType("TEXT");

                    b.Property<string>("Txt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Infos");
                });
#pragma warning restore 612, 618
        }
    }
}
