// <auto-generated />
using BlazorIoTBridge.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorIoTBridge.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BlazorIoTBridge.Shared.Info", b =>
                {
                    b.Property<string>("DeviceGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("DEVICE_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_COMPATIBILITY_ENDPOINT")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_COMPATIBILITY_PATH")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_CONNECTION_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("EVENT_HUBS_SAS_KEY")
                        .HasColumnType("TEXT");

                    b.Property<string>("HUB_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("IOTHUB_DEVICE_CONN_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("IOTHUB_HUB_CONN_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("SERVICE_CONNECTION_STRING")
                        .HasColumnType("TEXT");

                    b.Property<string>("SHARED_ACCESS_KEY_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("SYMMETRIC_KEY")
                        .HasColumnType("TEXT");

                    b.Property<string>("Txt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceGuid");

                    b.ToTable("Infos");
                });
#pragma warning restore 612, 618
        }
    }
}
